### ISSUE TITLE
根路由组件跳转显示存在问题

### ISSUE THREAD

**Issue by Kang-Yang** [feiyuchuixue/sz-admin#5]
1.点击 “系统管理”
![image](https://github.com/user-attachments/assets/df75bd38-48b4-4eb7-8515-b6222f3f7359)
2.会出现如下界面：
![image](https://github.com/user-attachments/assets/4f28d69d-8105-4f2c-acfe-2333056ef92a)

正常应该是不会有任何的tab页面出现，或者说点击根路由，返回至第一个子路由界面

**Comment by feiyuchuixue** [comment]
可按如下方式修改
![image](https://github.com/user-attachments/assets/4acf5357-8ef8-437b-b118-5a00df9676f9)

**Comment by feiyuchuixue** [comment]
已发布，更新main分支代码。
