### ISSUE TITLE
https://github.com/HalseySpicy/Geeker-Admin

### ISSUE THREAD

**Issue by zhangkaivictor** [feiyuchuixue/sz-admin#7]
请问一下，你的项目跟这个项目https://github.com/HalseySpicy/Geeker-Admin有什么区别吗？ 具体详说一下。 两者的源码我看了，不能说一模一样，只能说99.999999像。 但是我看我发的链接的初始提交时间比你的早的多啊，不知道阁下怎么给大家一个合理的解释呢？

**Comment by feiyuchuixue** [comment]
官网文档中说的很清楚，你也可以看看geeker-admin的置顶issue。你下载代码了，对比过了？
